import "../globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainHeader from "@/components/MainHeader";
import ComponentList from "@/components/ComponentList";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className={`flex flex-col w-full h-[100dvh]`}>
            <MainHeader />
            <div className={`flex justify-center items-start flex-1`}>
              <div className={`max-w-5xl w-full h-full flex flex-row gap-8 pt-8`}>
                <ComponentList />
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
