
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import {ModeToggle} from "@/components/ModeToggle";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <div className={`flex flex-col w-full h-[100dvh]`}>
        <div className={`flex flex-row w-full h-16 p-4 broder-b border-border justify-end`}>
          <ModeToggle />
        </div>
        <div className={`flex justify-center items-start flex-1`}>
          <div className={`max-w-5xl w-full h-full flex flex-row gap-8 pt-8`}>
            <div className={`h-full flex flex-col px-8 pb-8 max-w-[15rem]`}>
              <div className={'whitespace-nowrap text-sm text-foreground font-semibold mb-1 py-1'} >
                Components
              </div>
              <Link href={'/components/moving-tabs'} className={`whitespace-nowrap hover:underline text-muted-foreground text-sm py-1`} > Moving Tabs </Link>
              <Link href={'/components/apple-unbox-slider'} className={`whitespace-nowrap hover:underline text-muted-foreground text-sm py-1`} > Apple Unbox Slider </Link>
              <Link href={'/components/apple-unbox-slider-2'} className={`whitespace-nowrap hover:underline text-muted-foreground text-sm py-1`} > Apple Unbox Slider 2 </Link>
              <Link href={'/components/mitosis'} className={`whitespace-nowrap hover:underline text-muted-foreground text-sm py-1`} > Mitosis </Link>
              <Link href={'/components/mitosis'} className={`whitespace-nowrap hover:underline text-muted-foreground text-sm py-1`} > Mitosis </Link>
            </div>
            {children}
          </div>
        </div>
      </div>
  );
}
